import express from "express";
import authRoute from "./authentication/auth.route";
import adminRoute from "./authentication/admin.route";
import categoryRoute from "./category/category.route";
import subcategoryRoute from "./subcategory/subcategory.route";
import productRoute from "./product/product.route";
import publicProductRoute from "./public/product.route";
import galleryRoute from "./gallery/gallery.route";
import teammemberRoute from "./teammember/teammember.route";
import inquiryRoute from "./inquiry/inquiry.route";
import replyRoute from "./reply/reply.route";
import careerRoute from "./career/career.route";
import applicationRoute from "./application/application.route";
import faqRoute from "./faq/faq.route";
import blogRoute from "./blog/blog.route";
import videoRoute from "./video/video.routes";
import downloadCategoryRoute from "./download-category/download-category.route";
import productDownloadRoute from "./product-download/product-download.route";
import contactRoute from "./contact/contact.route";
import categoryAnalyticsRoute from "./analytics/category.analytics.route";
import seoAnalyticsRoute from "./analytics/seo.analytics.route";
import userAnalyticsRoute from "./analytics/user.analytics.route";
import reviewRoute from "./review/review.route";
import seoMetadataRoute from "./seo-metadata/seo-metadata.route";

const router = express.Router();

router.use("/auth", authRoute);
router.use("/admin", adminRoute);
router.use("/category", categoryRoute);
router.use("/subcategory", subcategoryRoute);
router.use("/product", productRoute);
router.use("/gallery", galleryRoute);
router.use("/team", teammemberRoute);
router.use("/inquiry", inquiryRoute);
router.use("/reply", replyRoute);
router.use("/career", careerRoute);
router.use("/application", applicationRoute);
router.use("/faq", faqRoute);
router.use("/blog", blogRoute);
router.use("/contact", contactRoute);
router.use("/video", videoRoute);
router.use("/review", reviewRoute);
router.use("/download-category", downloadCategoryRoute);
router.use("/product-download", productDownloadRoute);
router.use("/seo-metadata", seoMetadataRoute);
router.use("/analytics/category", categoryAnalyticsRoute);
router.use("/analytics/seo", seoAnalyticsRoute);
router.use("/analytics/user", userAnalyticsRoute);
router.use("/public/product", publicProductRoute);

export default router;
