import { IProduct } from "../dto/product/product.interface";

export function newProductMailTemplate(data: IProduct): string {
  return `
  <!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>New Product Listed - Plaza Sales</title>
      <style>
        * { box-sizing: border-box; }
        body {
          margin: 0;
          padding: 0;
          font-family: "Helvetica", "Arial", sans-serif;
          background-color: #f8f9fa;
          color: #333;
        }
        .container {
          max-width: 600px;
          margin: 20px auto;
          background: #ffffff;
          border-radius: 10px;
          box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
          overflow: hidden;
        }
        .header {
          background: #004aad;
          color: #fff;
          text-align: center;
          padding: 20px;
        }
        .header img {
          width: clamp(60px, 15vw, 120px);
          height: auto;
          border-radius: 50%;
          background: #fff;
          padding: 8px;
          margin-bottom: 10px;
        }
        .content {
          padding: 20px;
        }
        .content h2 {
          color: #DA2B34;
          margin-top: 0;
        }
        .content p {
          font-size: 15px;
          line-height: 1.6;
          margin: 6px 0;
        }
        .product-image {
          width: 100%;
          max-width: 400px;
          height: auto;
          display: block;
          margin: 10px auto;
          border-radius: 10px;
        }
        .divider {
          border-top: 1px solid #ddd;
          margin: 15px 0;
        }
        .footer {
          background: #f1f1f1;
          text-align: center;
          padding: 15px;
          font-size: 13px;
          color: #666;
        }
        @media screen and (max-width: 600px) {
          .container { margin: 10px; }
          .content { padding: 15px; }
        }
        @media screen and (max-width: 480px) {
          .header img {
            width: clamp(50px, 20vw, 100px);
            padding: 6px;
          }
        }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <img src="https://pub-969c218ddb2f4a29bbe25940c8760402.r2.dev/uploads/main-logo.png" alt="Plaza Sales Logo" />
          <h1>Plaza Sales</h1>
        </div>

        <div class="content">
          <h2>🆕 New Product Listed!</h2>
          <p><strong>Product Name:</strong> ${data.name}</p>
          <p><strong>Price:</strong> $${data.price}</p>
          ${
            data.imageUrl
              ? `<img src="${data.imageUrl}" alt="${data.name}" class="product-image" />`
              : ""
          }
          <div class="divider"></div>
          <p>Check it out now on Plaza Sales!</p>
        </div>

        <div class="footer">
          <p>This message was automatically generated by <strong>Plaza Sales</strong>.</p>
          <p>© ${new Date().getFullYear()} Plaza Sales. All rights reserved.</p>
        </div>
      </div>
    </body>
  </html>
  `;
}
